services:
  - type: web
    name: mlsite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mlsite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mlsite.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true 